omni_controller:
  ros__parameters:
    mode_orientation: odometry

path_tracking:
  ros__parameters:
    rate: 50.0
    kp: 35.0
    ki: 0.5

node_path_generate:
  ros__parameters:
    orientation: follow_line

  # orientation mode:
  # fixed
  # follow_line
  # setpoint
  # follow_line_&_setpoint