omni_controller:
  ros__parameters:
    mode_orientation: odometry
    wheel_diameter: 0.1016

path_tracking:
  ros__parameters:
    orientation: setpoint
    step: 100

    pid_x-Kp: 20.0
    pid_x-Ki: 0.0
    pid_x-Kd: 0.2

    pid_y-Kp: 20.0
    pid_y-Ki: 0.0
    pid_y-Kd: 0.2

    pid_w-Kp: 20.0
    pid_w-Ki: 0.0
    pid_w-Kd: 0.2

    limit_speed_on_x: 3.0
    limit_speed_on_y: 3.0
    limit_speed_on_w: 1.0

  # orientation mode:
  # fixed
  # follow_line
  # setpoint
